#!/bin/sh

readonly files_target=$(    \
  find -type f -name "*$1*" \
  -not -name "README.md"    \
  -not -name ".gitignore"   \
)

for file in $files_target; do
  if [ ! -f $file ] || [ $file == $0 ]; then
    continue
  fi

  object_target=$(echo $file | sed -r "s/\.c/.o/g")
  file_target=$(echo $file | sed -r "s/\.c/.run/g")

  gcc -c $file -o $object_target
  gcc $object_target -o $file_target -lncurses

  $file_target

  rm -f $object_target $file_target
done