#!/bin/bash

while getopts ":a:b:" opt; do
  case $opt in
    a)
      echo "Option -a with argument $OPTARG"
      ;;
    b)
      echo "Option -b with argument $OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      ;;
  esac
done

shift $((OPTIND - 1))
echo "Remaining arguments: $@"